# Copyright 2022 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Intellij install folder
  become: true
  file:
    path: /opt/intellij
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Check if IntelliJ archive exists
  stat:
    path: ~/Downloads/intellij.tar.gz
  register: intellij_download

- name: Download Intellij Ultimate
  get_url:
    dest: ~/Downloads/intellij.tar.gz
    url: https://download.jetbrains.com/product?code=IIU&latest&distribution=linux
  when: not intellij_download.stat.exists

- name: extract into /opt/intellij
  unarchive:
    src: ~/Downloads/intellij.tar.gz
    dest: /opt/intellij
  when: not intellij_download.stat.exists

- name: create "active" symlink for intellij
  shell:
    chdir: /opt/intellij
    cmd: |
      find -maxdepth 1 -type d -name 'idea*' | head -n 1 | xargs -I{} ln -s --no-dereference --force {} active
  when: not intellij_download.stat.exists
      
- name: create /usr/local/bin/ intellij link
  become: true
  file:
    src: /opt/intellij/active/bin/idea
    dest: /usr/local/bin/idea
    state: link

- name: Idea inotify watch list
  copy: dest=/etc/sysctl.d/idea.conf src=idea.conf
  become: true
- name: refresh sysctl
  shell: sysctl -p --system
  become: true

# Clion install, doing way too much work in C++.

- name: Clion install folder
  become: true
  file:
    path: /opt/clion
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Check if clion archive exists
  stat:
    path: ~/Downloads/clion.tar.gz
  register: clion_download

- name: Download clion Ultimate
  get_url:
    dest: ~/Downloads/clion.tar.gz
    url: https://download.jetbrains.com/product?code=CL&latest&distribution=linux
  when: not clion_download.stat.exists

- name: extract into /opt/clion
  unarchive:
    src: ~/Downloads/clion.tar.gz
    dest: /opt/clion
  when: not clion_download.stat.exists

- name: create "active" symlink for clion
  shell:
    chdir: /opt/clion
    cmd: |
      find -maxdepth 1 -type d -name 'clion*' | head -n 1 | xargs -I{} ln -s --no-dereference --force {} active
  when: not clion_download.stat.exists

- name: create /usr/local/bin/ clion link
  become: true
  file:
    src: /opt/clion/active/bin/clion
    dest: /usr/local/bin/clion
    state: link