source ~/.core.zsh

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# theme
ZSH_THEME="lambda"

plugins=(debian cabal)
plugins+=($coreplugins)

source $ZSH/oh-my-zsh.sh

if [ -f ~/.dircolors ]; then
  eval `dircolors ~/.dircolors`
fi

#yes, I suck.
export EDITOR='nano -w'

#Find all of the haskell dirs, and put them on the path
haskell_bin_dirs=$(find /opt -type d -name 'bin')
haskell_bin_dirs=(${(@f)haskell_bin_dirs})

export PATH=~/.cabal/bin:${(j/:/)haskell_bin_dirs}:$PATH

# install the defalt ghc packages
function install-default-ghc-packages() {
  cabal update && cabal install hlint stylish-haskell ghc-mod
}