# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# theme
ZSH_THEME="cloud"

#plugins
plugins=(git debian git-extras colored-man autojump go zsh_reload dirhistory zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

if [ -f ~/.dircolors ]; then
  eval `dircolors ~/.dircolors`
fi

#yes, I suck.
export EDITOR='nano -w'

# do this because gb is our go tool
alias gbb="git branch"
unalias gb

# The next line updates PATH for the Google Cloud SDK.
source /google-cloud-sdk/path.zsh.inc

# The next line enables bash completion for gcloud.
source /google-cloud-sdk/completion.zsh.inc
