# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# theme
ZSH_THEME="lambda"

#plugins
plugins=(git debian git-extras colored-man autojump go zsh_reload dirhistory lein)

source $ZSH/oh-my-zsh.sh

if [ -f ~/.dircolors ]; then
  eval `dircolors ~/.dircolors`
fi

#yes, I suck.
export EDITOR='nano -w'