source ~/.core.zsh

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# theme
ZSH_THEME="lambda"

plugins=(debian lein)
plugins+=($coreplugins)

source $ZSH/oh-my-zsh.sh

if [ -f ~/.dircolors ]; then
  eval `dircolors ~/.dircolors`
fi

#yes, I suck.
export EDITOR='nano -w'