# Copyright 2025 Mark Mandel All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Symlink top-level config directories into ~/.config
  file:
    src: "{{ role_path }}/files/config/{{ item }}"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/{{ item }}"
    state: link
    force: true
  with_items: "{{ lookup('pipe', 'find ' + role_path + '/files/config -mindepth 1 -maxdepth 1 -type d -printf \"%f\\n\"').splitlines() }}"

- name: Symlink top-level config files into ~/.config
  file:
    src: "{{ role_path }}/files/config/{{ item }}"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/{{ item }}"
    state: link
    force: true
  with_items: "{{ lookup('pipe', 'find ' + role_path + '/files/config -mindepth 1 -maxdepth 1 -type f -printf \"%f\\n\"').splitlines() }}"
