---

# Setup standard home directories

- name: Make default home directories
  file: 
    path: "~/{{ item }}"
    state: directory
  with_items:
    - .config
    - Downloads
    - Pictures
    - Documents
    - Music
    - Videos
    - GoogleDrive

# TOXO: generate ~/.config/gtk-3.0/bookmarks with envsubst
