# Copyright 2024 Mark Mandel All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

# nerd font key path (starting, but not ending with '/')
- name: install JetBrainMono Nerd Font
  get_url:
    dest: ~/Downloads/JetBrainsMono.zip
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip
    force: false
- name: ensure font directory exists
  become: true
  file:
    path: /usr/share/fonts/nerd/jetbrains-mono
    state: directory
- name: unzip jetbrains fonts
  become: true
  unarchive:
    src: ~/Downloads/JetBrainsMono.zip
    dest: /usr/share/fonts/nerd/jetbrains-mono

- name: hyprland config directory
  file:
    path: ~/.config/hypr
    state: directory

- name: link hyprland config
  shell: |
    ln --force -s {{ role_path }}/files/config/hypr/hyprland.conf ~/.config/hypr/hyprland.conf

- name: make directory for dunst config
  file: path="~/.config/dunst" state=directory

- name: link dunst config
  shell: |
    ln --force -s {{ role_path }}/files/config/dunst/dunstrc ~/.config/dunst/dunstrc

- name: install hyprland and related packages
  become: true
  apt:
    name:
      - hyprland
      - xdg-desktop-portal-hyprland
      - nemo
      - nemo-fileroller
      - nemo-font-manager
      - nemo-compare
      - nwg-look
      - wofi
      - dunst
      - playerctl
      - pipewire
      - wireplumber
      - xwaylandvideobridge
      - qt6-wayland
      - waybar
      - wlr-rander
