

---

# nerd font key path (starting, but not ending with '/')
- name: install JetBrainMono Nerd Font
  get_url:
    dest: ~/Downloads/JetBrainsMono.zip
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip
    force: false
- name: ensure font directory exists
  become: true
  file:
    path: /usr/share/fonts/nerd/jetbrains-mono
    state: directory
- name: unzip jetbrains fonts
  become: true
  unarchive:
    src: ~/Downloads/JetBrainsMono.zip
    dest: /usr/share/fonts/nerd/jetbrains-mono
