# Copyright 2024 Mark Mandel All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Check for NVIDIA GPU
  shell: lspci | grep -i nvidia
  register: nvidia_check
  failed_when: false
  changed_when: false

# Info:
# https://wiki.debian.org/NvidiaGraphicsDrivers
# https://wiki.hyprland.org/Nvidia/
# https://docs.nvidia.com/datacenter/tesla/driver-installation-guide/debian.html#compute-only-headless-and-desktop-only-no-compute-installation

- name: Download NVIDIA CUDA keyring package
  become: true
  get_url:
    url: https://developer.download.nvidia.com/compute/cuda/repos/debian13/x86_64/cuda-keyring_1.1-1_all.deb
    dest: /tmp/cuda-keyring_1.1-1_all.deb
    mode: '0644'
  when: nvidia_check.rc == 0

- name: Install NVIDIA CUDA keyring package
  become: true
  apt:
    deb: /tmp/cuda-keyring_1.1-1_all.deb
  when: nvidia_check.rc == 0

- name: Update apt cache after adding NVIDIA repository
  become: true
  apt:
    update_cache: true
  when: nvidia_check.rc == 0

- name: Install nvidia drivers
  become: true
  apt:
    name:
      - nvidia-driver
      - nvidia-kernel-open-dkms
      - libnvidia-egl-wayland1
      - libnvidia-egl-gbm1
      - nvidia-vaapi-driver
  when: nvidia_check.rc == 0

- name: Set nvidia wayland modprobe options
  become: true
  copy:
    src: etc/modprobe.d/nvidia-wayland-options.conf
    dest: /etc/modprobe.d/nvidia-wayland-options.conf
    owner: root
    group: root
    mode: '0644'
  when: nvidia_check.rc == 0

- name: Run update-initramfs after setting modprobe options
  become: true
  shell: update-initramfs -u
  when: nvidia_check.rc == 0

- name: Set nvdia options and enable suspend and hibernate services.
  become: true
  shell: |
    echo 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX nvidia-drm.modeset=1 nvidia_drm.fbdev=1"' > /etc/default/grub.d/nvidia-modeset.cfg
    update-grub
    systemctl enable nvidia-suspend.service
    systemctl enable nvidia-hibernate.service
    systemctl enable nvidia-resume.service
  when: nvidia_check.rc == 0
