# Copyright 2026 Mark Mandel All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Add avengemedia danklinux OBS repository
  become: true
  shell: |
    echo 'deb http://download.opensuse.org/repositories/home:/AvengeMedia:/danklinux/Debian_Testing/ /' | tee /etc/apt/sources.list.d/home:AvengeMedia:danklinux.list
    curl -fsSL https://download.opensuse.org/repositories/home:AvengeMedia:danklinux/Debian_Testing/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/home_AvengeMedia_danklinux.gpg > /dev/null
  retries: 5
  delay: 5

- name: Pin ghostty to deprioritize from avengemedia danklinux OBS repository
  become: true
  copy:
    dest: /etc/apt/preferences.d/avengemedia-danklinux
    content: |
      Package: ghostty
      Pin: release o=obs://build.opensuse.org/home:AvengeMedia:danklinux/Debian_Testing
      Pin-Priority: -1

- name: Install quickshell-git
  become: true
  apt:
    name:
      - quickshell-git
    update_cache: true